name: CI sur z/OS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @zowe/cli
      - run: mkdir -p ~/.zowe
      - run: cp src/zowe.config.json ~/.zowe/
      - run: zowe zos-files list ds "Z82165.CBL" --max-items 5
