name: CI sur z/OS

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Zowe CLI
        run: npm install -g @zowe/cli

      - name: Initialiser config basique
        run: |
          zowe config auto-init \
            --host 204.90.115.200 \
            --port 6800 \
            --user Z82165 \
            --pass "PLA700HR" \
            --reject-unauthorized false

      - name: Modifier le profil pour RSE
        run: |
          zowe config set profiles.zosmf.properties.basePath rseapi
          zowe config set profiles.zosmf.properties.protocol https

      - name: Tester connexion
        run: |
          zowe zos-files list ds "Z82165.*" --max-items 5
