name: CI sur z/OS

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Zowe CLI
        run: npm install -g @zowe/cli

      - name: Configurer Zowe
        run: |
          zowe config auto-init \
            --host ${{ secrets.ZOSMF_HOST }} \
            --port ${{ secrets.ZOSMF_PORT }} \
            --user ${{ secrets.ZOSMF_USER }} \
            --pass ${{ secrets.ZOSMF_PASS }} \
            --reject-unauthorized false

      - name: Tester connexion z/OS
        run: zowe zos-files list ds "*.ZOWE.*" --max-items 5
